sudo: required
arch:
 repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
 packages:
  # pacman packages
  - cmake
  - make
  - gcc
  - g++
 script:
  - ./build-repo
  - sudo ./build.sh -v
  # build other
  - wget -O curlpp-0.8.1.tar.gz https://github.com/jpbarrette/curlpp/archive/v0.8.1.tar.gz
  - tar -xf curlpp-0.8.1.tar.gz
  - cd curlpp-0.8.1
  - mkdir cmake_build
  - cd cmake_build
  - cmake -D CMAKE_CXX_COMPILER=`which ${CXX_COMPILER}` -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" ..
  - sudo make install
  - wget -O ncurses-6.1.tar.gz https://invisible-mirror.net/archives/ncurses/ncurses-6.1.tar.gz
  - tar -xf ncurses-6.1.tar.gz
  - cd ncurses-6.1
  - ./configure
  - make
  - sudo make install
  # build project
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  # Info
  - gcc --version
  - g++ --version
  - cmake --version
  - make --version

script:
 - "travis_wait 30 sleep 1800 &"
- curl -s https://raw.githubusercontent.com/fossasia/arch-travis/master/arch-travis.sh | bash