language: cpp
sudo: required
dist: trusty
os: linux
compiler: gcc
addons:
    apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++', 'gcc', 'make']
        env:
            - CXX_COMPILER=g++
            - C_COMPILER=gcc

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -q
    - sudo apt-get install gcc-8.1 -y
    - pushd ~
    - wget -O curlpp-0.8.1.tar.gz https://github.com/jpbarrette/curlpp/archive/v0.8.1.tar.gz
    - tar -xf curlpp-0.8.1.tar.gz
    - cd curlpp-0.8.1
    - mkdir cmake_build
    - cd cmake_build
    - cmake -D CMAKE_CXX_COMPILER=`which ${CXX_COMPILER}` -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" ..
    - sudo make install
    - wget -O ncurses-6.1.tar.gz https://invisible-mirror.net/archives/ncurses/ncurses-6.1.tar.gz
    - tar -xf ncurses-6.1.tar.gz
    - cd ncurses-6.1
    - ./configure
    - make
    - sudo make install
    - wget https://github.com/Kitware/CMake/archive/v3.11.4.tar.gz
    - tar -xf v3.11.4.tar.gz
    - cd CMake-3.11.4
    - ./bootstrap && make && sudo make install
    - popd

script:
    - mkdir build
    - cd build
    - cmake ..
    - make VERBOSE=1
    # Info
    - gcc --version
    - g++ --version
    - cmake --version
    - make --version