language: cpp
sudo: required
dist: trusty
os: linux
compiler: gcc
addons:
    apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++', 'gcc', 'cmake', 'libncurses5-dev']
        env:
            - CXX_COMPILER=g++
            - C_COMPILER=gcc

before_install:
    - pushd ~
    - wget -O curlpp-0.8.1.tar.gz https://github.com/jpbarrette/curlpp/archive/v0.8.1.tar.gz
    - tar -xf curlpp-0.8.1.tar.gz
    - cd curlpp-0.8.1
    - mkdir cmake_build
    - cd cmake_build
    - cmake -D CMAKE_CXX_COMPILER=`which ${CXX_COMPILER}` -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" ..
    - sudo make install
    - wget http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libncurses6_6.1+20180210-4ubuntu1_amd64.deb
    - sudo dpkg -i libncurses6_6.1+20180210-4ubuntu1_amd64.deb
    - popd
script:
    - mkdir build
    - cd build
    - cmake ..
    - make