language: cpp
compiler: gcc
os: linux
before_install:
    - sudo apt-get update -q
    - sudo apt-get install cmake ninja make libncurses5-dev
addon:
        apt:
            sources:
                - ubuntu-toolchain-r test
            packages:
                - cmake=3.10
                - make
                - ninja=1.5
                - libncurses5-dev
script:
        - mkdir build && cd build
        - cmake .. && make hoshiMenu
