language: cpp
compiler: gcc
os: linux
before_install:
    - sudo apt-get update -q
    - sudo apt-get install make libncurses5-dev
addon:
        apt:
            sources:
                - ubuntu-toolchain-r test
            packages:
                - cmake
                - make
                - ninja
                - libncurses5-dev
script:
        - mkdir build && cd build
        - cmake .. && make
