language: cpp
compiler:
  - gcc
os:
  - linux
dist: trusty
before_install: sudo apt-get install -y make cmake ninja libncurses-dev 
addons:
  update: true
   package:
    - cmake
    - ninja
    - make
    - libncurses-dev
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./hoshiMenu