language: cpp
compiler: gcc
os: linux
before_install:
    - sudo apt-get update -q
    - sudo apt-get install make libncurses5-dev
addon:
        apt:
            sources:
                - ubuntu-toolchain-r test
            packages:
                - cmake=3.10
                - make
                - ninja=1.5
                - libncurses5-dev
install:
    - version=3.12 && build=0
    - mkdir ~/temp && cd ~/temp
    - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
    - tar -xzvf cmake-$version.$build.tar.gz
    - cd cmake-$version.$build/
    - ./bootstrap
    - make -j4
    - sudo make install
script:
        - mkdir build && cd build
        - cmake .. && make hoshiMenu
