language: cpp
compiler: gcc
os: linux
addon:
        sources:
            - ubuntu-toolchain-r test
        packages:
            - cmake
            - make
            - ninja
            - libncurses-dev
script:
        - mkdir build && cd build
        - cmake .. && make hoshiMenu
